[build]
  publish = "dashboard/dist"
  command = "npm run build:all"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production=false"

# SPA redirects for dashboard
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy for development
[[redirects]]
  from = "/api/*"
  to = "http://localhost:5000/api/:splat"
  status = 200
  force = false

[dev]
  command = "npm run dev:dashboard"
  port = 5173
  publish = "dashboard/dist"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
